# Prevent chorus fruit teleportation within 8 blocks of a barrier
block-chorus-teleportation: true

# Prevent entities from getting through barriers
block-entities:
  enabled: true

repel-projectiles:
  enabled: true
  # Enable only for projectiles shot by a player (It may reduce lag)
  only-from-player: false

version: 2
