name: Lint Project

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Publish Checkstyle Report
        uses: actions/upload-artifact@v2
        with:
          name: Checkstyle Report
          path: build/reports/checkstyle/main.html
